app/main/urls.py
from django.urls import re_path, include
from django.contrib import admin

urlpatterns = [
    re_path('', include('myshop.urls')),
    re_path(r'^admin/', admin.site.urls),
]

app/myshop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("login/", views.LoginPage.as_view(), name="login"),
    path("logout/", views.LogoutPage.as_view(), name="logout"),
    path("", views.HomePage.as_view(), name="index"),
    path("inactive-products", views.ProductInactiveListView.as_view(),
         name="products_inactive"),
    path("product/<int:pk>/", views.ProductDetailView.as_view(),
         name="product_detail"),
    path("product/<int:pk>/edit", views.ProductEditView.as_view(),
         name="product_edit"),
    path("product/new", views.ProductCreateView.as_view(), name='product_create'),
    path("product/<int:pk>/delete",
         views.ProductDeleteView.as_view(), name='product_delete'),
    path('category/<slug:slug>/', views.ProductByCategoryListView.as_view(), name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/myshop/models.py
import random

from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name="Name")
    order = models.IntegerField("order", default=20)
    slug = models.SlugField(unique=True, null=True)
    parent_category = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True, related_name='subcategories')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    @classmethod
    def get_category_by_level(cls):
        categs = cls.objects.filter(parent_category=None).order_by("order").all()
        res = [
            {
                "name": categ.name,
                "slug": categ.slug,
                "subcategs":categ.subcategories.order_by("order").all()
            }
            for categ in categs
        ]
        return res

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name="Name")
    active = models.BooleanField(verbose_name="Show", default=True)
    price = models.PositiveIntegerField(verbose_name="Price")
    category = models.ForeignKey(
        Category, verbose_name="Category", null=True, on_delete=models.SET_NULL)
    thumbnail = models.ImageField(
        upload_to='thumbnail/', default='thumbnail/default.png', verbose_name='Thumbnail')
    description = models.TextField(
        verbose_name='Description', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'pk': self.pk})

    def get_related_products(self):
        all_products = Product.objects.exclude(id=self.id)

        if all_products.count() > 5:
            # Randomly select 4 products
            # TODO: Implement better strategy
            related_products = random.sample(list(all_products), 4)
        else:
            related_products = all_products

        return related_products


class ProductImage(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name="images",
                                null=False)
    image = models.ImageField()


class Thumbnail(models.Model):
    image = models.ImageField()

app/myshop/forms.py
from typing import Any
from django import forms

from .models import Product, ProductImage


class ProductForm(forms.ModelForm):
    thumbnail = forms.ImageField(label="Thumbnail")

    class Meta:
        model = Product
        fields = "__all__"


class ImageForm(forms.ModelForm):
    image = forms.ImageField(
        label="Image",
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
        required=False,
    )

    class Meta:
        model = ProductImage
        fields = ("image",)

app/myshop/views.py
from typing import Any
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView
)
from django.db.models import Q

from .forms import ImageForm, ProductForm
from .models import Category, Product, ProductImage, Thumbnail


class LoginPage(LoginView):
    template_name = "myshop/login.html"


class LogoutPage(LogoutView):
    next_page = "/login"


class HomePage(ListView):
    queryset = Product.objects.filter(active=True)
    template_name = "myshop/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["thumnails"] = Thumbnail.objects.all()
        return context


class ProductInactiveListView(LoginRequiredMixin, ListView):
    queryset = Product.objects.filter(active=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["inactive"] = True
        return context


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_id = self.get_object()
        context["images"] = ProductImage.objects.filter(product=product_id)
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["imageform"] = ImageForm()
        return context

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = ProductForm(request.POST, request.FILES)
        files = request.FILES.getlist("image")

        if form.is_valid():
            product_instance = form.save(commit=False)
            product_instance.user = request.user
            product_instance.save()

            for image_file in files:
                ProductImage.objects.create(
                    product=product_instance, image=image_file)

            messages.success(request, 'New Product Added')

            return redirect(
                reverse(
                    'product_detail',
                    kwargs={'pk': product_instance.pk}
                ))
        else:
            return HttpResponse(form.errors)


class ProductEditView(LoginRequiredMixin, UpdateView):
    model = Product
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()

        context["imageform"] = ImageForm()
        context["images"] = ProductImage.objects.filter(product=product)
        return context

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        res = super().post(request, *args, **kwargs)
        files = request.FILES.getlist("image")

        if not files:
            return res
        
        product = self.get_object()
        product.images.all().delete()
        for image_file in files:
            ProductImage.objects.create(
                product=product, image=image_file)

        return res


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("index")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class ProductByCategoryListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        slug = self.kwargs['slug']
        category = get_object_or_404(Category, slug=slug)
        filter_cond = Q(category=category)
        for subcateg in category.subcategories.all():
            filter_cond |= Q(category=subcateg)

        return Product.objects.filter(filter_cond)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        context['category'] = get_object_or_404(Category, slug=slug)
        return context

app/myshop/templates/myshop/base.html
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />

  {% block title %}
  {% endblock %}
  {% load static %}
  <!-- bootstrap core css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'myshop/css/style.css' %}" />
  <!-- responsive style -->
  <link rel="stylesheet" href="{% static 'myshop/css/responsive.css' %}" />
  {% block custom_style %}
  {% endblock %}
</head>

<body>
  <header class="header_section">
    <nav class="navbar navbar-expand-lg fixed-top custom_nav-container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class=""></span></button>
      <a class="navbar-brand flex-grow-1" href="/"><span>Vi tính Duy Quang</span></a>
      <div class="collapse navbar-collapse flex-grow-1 justify-content-center" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Trang chủ</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu inline">
              {% for categ in categories %}
                <li class="dropdown">
                  {% if categ.subcategs %}
                  <a class="dropdown-item dropdown-toggle" 
                    id="navbarDropdownMenuLink2"
                    data-bs-toggle="dropdown" 
                    aria-haspopup="true" 
                    aria-expanded="false"
                    href="{% url 'category' categ.slug %}"
                  >{{ categ.name }}</a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
                    {% for sub_categ in categ.subcategs %}
                    <li>
                      <a class="dropdown-item" href="{% url 'category' sub_categ.slug %}">
                        {{ sub_categ.name }}
                      </a>
                    </li>
                    {% endfor %}
                  </ul>
                  {% else %}
                  <a class="dropdown-item" 
                    href="{% url 'category' categ.slug %}"
                  >{{ categ.name }}</a>
                  {% endif %}
                </li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#shop_section">Sản phẩm</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#info_section">Liên hệ</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Action
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a href="{% url 'product_create' %}" class="dropdown-item">Thêm sp mới</a>
                {% if not inactive %}
                  <a href="{% url 'products_inactive' %}" class="dropdown-item">Sp bị ẩn</a>
                {% endif %}
                <a href="{% url 'logout' %}" class="dropdown-item">
                  <i class="fa fa-sign-out" aria-hidden="true"></i>
                  <span>Đăng xuất</span>
                </a>
              </div>
            </li>
          {% endif %}
          {% comment %}TODO: Implement search{% endcomment %}
          {% comment %}
          <form class="form-inline">
            <button class="btn nav_search-btn" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          </form>
          {% endcomment %}
        </ul>
      </div>
    </nav>
  </header>
  {% block content %}
  {% endblock %}
</body>

<script>
  let dropdowns = document.querySelectorAll('.dropdown-toggle')
  dropdowns.forEach((dd)=>{
      dd.addEventListener('mouseover', function (e) {
          var el = this.nextElementSibling
          el.style.display = el.style.display==='block'?'none':'block'
      })
      dd.addEventListener('mouseout', function (e) {
          var el = this.nextElementSibling
          el.style.display = el.style.display==='block'?'block':'none'
      })
  })
</script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script src="js/custom.js"></script>

app/myshop/templates/myshop/index.html
  {% extends 'myshop/product_list.html' %}
  {% load humanize %}

  {% block title %}
    <title>Trang chủ</title>
  {% endblock %}
  {% block slider %}
    <!-- slider section -->
    <section class="slider_section">
      <div class="slider_container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="2000">
          <div class="carousel-inner">
            {% for thumbnail in thumnails %}
            <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-4">
                    <div class="detail-box">
                      <h1>
                        Uy Tín<br>
                        Chất Lượng<br>
                        Đảm Bảo
                      </h1>
                      <p>
                        Quốc lộ 1A, Khu phố 2, TT Hòa Vinh, Đông Hòa
                      </p>
                      <a href="">
                        Liên hệ ngay
                      </a>
                    </div>
                  </div>
                  <div class="col-md-8">
                    <div class="img-box">
                      <img src="{{ thumbnail.image.url }}" alt="" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="carousel_btn-box">
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <i class="fa fa-arrow-left" aria-hidden="true"></i>
              <span class="sr-only">Previous</span>
            </a>
            <img src="images/line.png" alt="" />
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <i class="fa fa-arrow-right" aria-hidden="true"></i>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- end slider section -->
  {% endblock %}

app/myshop/templates/myshop/login.html
{% extends "myshop/base.html" %}

{% block title %}
<title>Login</title>
{% endblock title%}

{% block content %}

<div class="container layout_padding2">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="login-container">
                <h2 class="text-center">Login</h2>
                {% if next %}
                <form action="{% url 'login' %}?next={{ next }}" method="post" >
                {% else %}
                <form method="post" action="{% url 'login' %}" class="login-form">
                {% endif %}
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Username:</label>
                        <input type="text" id="id_username" name="username" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        <input type="password" id="id_password" name="password" class="form-control" required>
                    </div>
                    {% if form.errors %}
                    <p class="errors">Your username and password didn't match. Please try again.</p>
                    {% endif %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-dark btn-block">Login</button>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/myshop/templates/myshop/product.html
<!doctype html>
<html>
<head>
<title>UI Design</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta charset=-"utf-8">
    {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
  <link rel="stylesheet" href="{% static 'myshop/css/product_style.css' %}" />
</head>
<body> 
<div class="outer">
  <div class="btn-group">
    <a class="btn btn-outline-info" style="margin-left: 20px; margin-top: 20px;" href="/">Back</a>
  </div>
  <div class="center-wrapper">
    <div class="container-fluid content">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-6 shoe-slider">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for image in images %}
                 <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"><img decoding="async" src="{{image.image.url}}" class="d-block w-100" alt="..."></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner">
                {% for image in images %}
                {% if forloop.counter0 == 0 %}
                <div class="carousel-item active">
                {% else %}
                <div class="carousel-item ">
                {% endif %}
                    <img decoding="async" src="{{image.image.url}}" class="d-block w-100" height="500" alt="...">
                </div>
              {% endfor %}
            </div> 
          </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6 shoe-content">
          <div class="text1">
            <h2>{{ product.name }}</h2>
            {% comment %} <span>SEA BLUE & WHITE</span> {% endcomment %}
          </div>
          <div class="text2">
            {{ product.price }}
          </div>
          <div class="text3">
            Text 3
          </div> 
          <div class="text4">
            DESCRIPTION
          </div> 
          <div class="text5">
            {{ product.description|linebreaks }}
          </div> 
          <div class="btn-wrapper">
            <span class="btn">BUY</span> 
            <span class="qantity">
              <div>
                <i class="fas fa-minus"></i>
                <span class="one">1</span>
                <i class="fas fa-plus"></i>
              </div>
              <div class="quantity-text">QUANTITY</div>
            </span> 
            <div class="social-icons">
              <i class="fab fa-twitter"></i>
              <i class="fab fa-pinterest-p"></i>
              <i class="fab fa-facebook-f"></i>
            </div> 
          </div> 
        </div>
      </div>
    </div>
  </div> 
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

app/myshop/templates/myshop/product_detail.html
{% extends "myshop/base.html" %}
{% load humanize %}

{% block custom_style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'myshop/css/product_style.css' %}" />
{% endblock custom_style %}
{% block title %}
  <title>{{product.name}}</title>
{% endblock title %}
{% block content %}
<div class="outer">
  <div class="btn-group-vertical">
    <a class="btn btn-outline-info" style="margin-left: 20px; margin-top: 20px;" href="/">Quay lại</a>
    {% if request.user.is_authenticated %}
      <a class="btn btn-outline-warning" 
        style="margin-left: 20px; margin-top: 20px;"
        href="{% url 'product_edit' product.id %}">
        Sửa
      </a>
      <a class="btn btn-outline-danger" 
        style="margin-left: 20px; margin-top: 20px;" 
        onclick="return confirm('Are you sure?');" 
        href="{% url 'product_delete' product.id %}">
        Xóa
      </a>
    {% endif %}
  </div>
    <div class="container-fluid content">
      <div class="row">
        <div class="col-8 col-sm-8 col-md-8 product-slider">
          <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for image in images %}
                <li data-target="#carouselIndicators" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner">
              {% for image in images %}
              {% if forloop.counter0 == 0 %}
                <div class="carousel-item active">
              {% else %}
                <div class="carousel-item">
              {% endif %}
                  <img decoding="async" 
                      src="{{image.image.url}}" 
                      class="d-block w-100 product-img center hover-opacity" 
                      alt="..."
                      onClick="onClick(this)">
              </div>
              {% endfor %}
              <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon bg-dark rounded-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon bg-dark rounded-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
        <div id="modal01" class="expand-img" onclick="this.style.display='none'">
          <div class="expand-img-content animate-zoom">
            <img id="img01" style="max-width: 100%; max-height: 100%; height: auto;">
          </div>
        </div>
        <div class="col-4 col-sm-4 col-md-4 product-content">
          <div class="text1">
            <h3>{{ product.name }}</h3>
          </div>
          <div class="is-divider"></div>
          <div class="text2">
            {{ product.price|floatformat:0|intcomma }}
          </div>
          <a href="https://github.com/Vix-Nguyen">
            <div class="btn-wrapper">
              <span class="btn">MUA LUÔN</span> 
            </div>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="text3">
          <h5>Thông số kỹ thuật</h5>
          <div class="is-divider"></div>
          {{ product.description|linebreaks }}
        </div> 
      </div>
      <div class="big-divider"></div>
      <div class="m-1">
        <h4>Sản phẩm khác</h4>
        <div class="row shop_section">
          {% for related_product in product.get_related_products %}
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="box">
              <a href="{% url 'product_detail' related_product.id %}">
                <div class="img-box related-product">
                  <img src="{{ related_product.thumbnail.url }}" alt="" />
                </div>
                <div class="detail-box mt-3">
                  <h6>{{ related_product.name }}</h6>
                </div>
                <div class="price">
                  <h6>
                    <span> {{ related_product.price|floatformat:0|intcomma }} </span>
                  </h6>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
    </div>
</div>

<script>
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
}
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
{% endblock content %}

app/myshop/templates/myshop/product_manage.html
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon" />
  
    <title>Home</title>
    {% load static %}
    <!-- slider stylesheet -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
    />
  
    <!-- bootstrap core css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'myshop/css/bootstrap.css' %}"
    />
  
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'myshop/css/style.css' %}" />
    <!-- responsive style -->
    <link rel="stylesheet" href="{% static 'myshop/css/responsive.css' %}" />
  </head>
  
  <body>
    <header class="header_section">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="#">
          <span>
            My Shop
          </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav  ">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#shop_section">
                Shop
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#footer_section">Contact Us</a>
            </li>
          </ul>
          <div class="user_option">
          {% if user.is_staff %}
            <div class="col">
                <a href="{% url 'myshop:create_product' %}" class="btn btn-outline-success"> Add Product </a>
            </div>
          {% endif %}
            {% comment %} TODO: Implement search {% endcomment %}
            {% comment %} <form class="form-inline ">
              <button class="btn nav_search-btn" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form> {% endcomment %}
          </div>
        </div>
      </nav>
    </header>
    <!-- shop section -->
    <section id="shop_section" class="shop_section layout_padding">
      <div class="container">
        <div class="heading_container heading_center">
          <h2>Latest Products</h2>
        </div>
        {% if product_list %}
        <div class="row">
          {% for product in product_list %}
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="box">
              <a href="{% url 'myshop:product' product.id %}">
                <div class="img-box">
                  <img src="{{product.thumbnail.url}}" alt="" />
                </div>
                <div class="detail-box">
                  <h6>{{ product.name }}</h6>
                  <h6>
                    Price
                    <span> {{ product.price }} </span>
                  </h6>
                </div>
                <div class="new">
                  <span> New </span>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
        {% else %}
        <p>No products to show.</p>
        {% endif %}
        {% comment %} <div class="btn-box">
          <a href=""> View All Products </a>
        </div> {% endcomment %}
      </div>
    </section>
  
    <!-- end shop section -->
    <script src="js/jquery-3.4.1.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script src="js/custom.js"></script>
  </body>